<div class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
<aside id="aside" role="complementary">
<h1>Categories</h1>			
<div class="textwidget"><div class="check">
<?php
	$args = $this->get('args',array('category__in'=> array()));
	$categories = get_categories(array(
		'show_option_all'    => '',
			'orderby'            => 'name',
			'order'              => 'ASC',
			'style'              => 'list',
			'show_count'         => 1,
			'hide_empty'         => 0,
			'use_desc_for_title' => 1,
			'child_of'           => 0,
			'feed'               => '',
			'feed_type'          => '',
			'feed_image'         => '',
			'exclude'            => '',
			'exclude_tree'       => '',
			'include'            => '',
			'hierarchical'       => 1,
			'title_li'           => __( 'Categories' ),
			'show_option_none'   => __( 'No categories' ),
			'number'             => null,
			'echo'               => 1,
			'depth'              => 0,
			'current_category'   => 0,
			'pad_counts'         => 0,
			'taxonomy'           => 'category',
			'walker'             => null
   	));
?>
<?php foreach($categories as $category): ?>
<input
	<?php if(in_array($category->term_id, $args['category__in'])):?>
	checked="checked"
	<?php endif;?>
	onchange="form.submit()"
	name="cat[<?php
						$cat = $category->term_id;
						print $cat;
						?>]"
	id="cat[<?php print $cat; ?>]"
	type="checkbox"
	value="<?php print $cat; ?>" />
	<label for="cat[<?php print $cat; ?>]">&nbsp;<?php print $category->name; ?></label>
<?php endforeach; ?>
<!--                             <input type="checkbox" value="0" id="educationCheck" name="education" /><label for="educationCheck">Education</label>
                            <input type="checkbox" value="0" id="transportCheck" name="transport" /><label for="transportCheck">Transport</label>
                            <input type="checkbox" value="0" id="energyCheck" name="energy" /><label for="energyCheck">Energy</label>
                            <input type="checkbox" value="0" id="waterCheck" name="water" /><label for="waterCheck">Water</label>
                            <input type="checkbox" value="0" id="businessCheck" name="business" /><label for="businessCheck">Business</label>
                            <input type="checkbox" value="0" id="sensorsCheck" name="sensors" /><label for="sensorsCheck">Sensors</label>
                            <input type="checkbox" value="0" id="statisticsCheck" name="statistics" /><label for="statisticsCheck">Statistics</label>
                            <input type="checkbox" value="0" id="environmentCheck" name="environment" /><label for="environmentCheck">Environment</label>
-->                            
</div></div>
</aside>
</div>