<div class="col-sm-3 col-lg-2 taxonomy">
  <aside id="aside" role="complementary">
    <h1>Categories</h1>			
    <div class="textwidget">
      <div class="check">
<?php
	$args = $this->get( 'args', array('category__in'=> array()) );
	$categories = get_categories(array(
		'hierarchical'     => TRUE,
		'orderby'          => 'count',
		'title_li'         => __( 'Categories' ),
		'show_option_none' => __( 'No categories' ),
		'taxonomy'         => 'category'
   	));
?>
        <ul>
<?php foreach($categories as $category): ?>
          <li<?php if(!empty($category->category_parent)) print ' class="subcat"' ?>>
          <input
	<?php if(in_array($category->term_id, $args['category__in'])):?>
	checked="checked"
	<?php endif;?>
	onchange="form.submit()"
	name="cat[<?php print $category->term_id ?>]"
	id="cat[<?php print $category->term_id ?>]"
	type="checkbox"
	value="<?php print $category->term_id ?>"/>
	<label for="cat[<?php print $category->term_id; ?>]">&nbsp;<?php print $category->name; ?></label>
	      </li>
<?php endforeach; ?>
        </ul>
      </div>
    </div>
  </aside>
</div>