<?php
if ($this->has('label')) {
	if (!$this->has('label-for')) {
		$this->setParam('label-for', $this->get('id'));
	}
	echo '<label';
	$this->spitAttrs(array('class', 'style', 'for', 'onclick') , 'label-');
	echo '>';
	$this->smushed('label');
	echo '</label>';
}
echo '<input onblur="value=value.trim()" type="text"';
foreach($this->get('data', array()) as $da => $dv) {
	print ' ' . $da . '="' . $this->smush($dv) . '"';
}
$this->spitAttrs();
echo ' />';
$this->partial('field-error', array('errors' => $this->get('errors'), 'class' => $this->get('error-class', null)));
if($this->full('description')) : ?>
	<p class="description col-lg-offset-3 col-md-offset-3 col-sm-offset-4 col-lg-9 col-md-9 col-sm-8 col-xs-12">
	<?php $this->smushed('description'); ?> </p>
<?php endif;

