 <hr/>
 <div class="btn-toolbar">
 <div class="btn-group">
<?php if($this->get('prev', false)): ?>
<button class="btn-flat btn btn-primary" type="button" onclick="changeTab(this, false);">
<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Previous
</button>
<?php endif; ?>
<?php if($this->get('next', false)): ?>
<button class="btn-flat btn btn-primary" type="button" onclick="changeTab(this, true);">Next
<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
</button>
<?php endif;?>
</div>
<div class="btn-group pull-right">
<?php if($this->get('cancel', false)): ?>
<a href="<?php print $this->itemOf('cancel','href','?');?>" class="btn-flat btn btn-default"  >
<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel
</a>
<?php endif;?>
<?php if($this->get('save', false)): ?>
<button class="btn-flat btn btn-success" type="submit" name="button" value="save">
<span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Finish and Save
</button>
<?php endif;?>
</div>
</div>